// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentStatus } from "./AgentStatus";
import type { CollabAgentModelSource } from "./CollabAgentModelSource";
import type { CollabAgentModelSourceDetail } from "./CollabAgentModelSourceDetail";
import type { MemoryLink } from "./MemoryLink";
import type { ThreadId } from "./ThreadId";

export type CollabAgentSpawnEndEvent = { 
/**
 * Identifier for the collab tool call.
 */
call_id: string, 
/**
 * Thread ID of the sender.
 */
sender_thread_id: ThreadId, memory: MemoryLink | null, agent_type: string | null, model: string | null, model_provider_id: string | null, model_source: CollabAgentModelSource | null, model_source_detail: CollabAgentModelSourceDetail | null, 
/**
 * Thread ID of the newly spawned agent, if it was created.
 */
new_thread_id: ThreadId | null, 
/**
 * Optional nickname assigned to the new agent.
 */
new_agent_nickname?: string | null, 
/**
 * Optional role assigned to the new agent.
 */
new_agent_role?: string | null, 
/**
 * Initial prompt sent to the agent. Can be empty to prevent CoT leaking at the
 * beginning.
 */
prompt: string, 
/**
 * Last known status of the new agent reported to the sender agent.
 */
status: AgentStatus, };
