// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CollabAgentModelSourceDetail = "config_model_sub" | "session_cache" | "model_sub_vouch" | "auto_calibration" | "tool_model_override" | "role_config";
