// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GuardianAssessmentStatus } from "./GuardianAssessmentStatus";
import type { GuardianRiskLevel } from "./GuardianRiskLevel";
import type { JsonValue } from "./serde_json/JsonValue";

export type GuardianAssessmentEvent = { id: string, turn_id: string, status: GuardianAssessmentStatus, risk_score?: number, risk_level?: GuardianRiskLevel, rationale?: string, action?: JsonValue, };
