// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemoryLink = { scope_version: string | null, scope_kind: string | null, summary_sha256: string | null, binding_key: string | null, };
