// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryLink } from "./MemoryLink";

export type TurnCompleteEvent = { turn_id: string, last_agent_message: string | null, memory: MemoryLink | null, };
